services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.16
    container_name: pin40_search
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    ports:
      - "9201:9200"
      - "9301:9300"
    restart: always

###> sensiolabs/gotenberg-bundle ###
  gotenberg:
    image: 'gotenberg/gotenberg:8'
###< sensiolabs/gotenberg-bundle ###

###>volumes:
volumes:
  esdata:

